# Generated by Django 6.1.1 on 2026-09-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('game_description', models.TextField()),
                ('recommended_dpi', models.PositiveIntegerField()),
                ('recommended_sensitivity', models.CharField(max_length=50)),
                ('sensitivity_description', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['game_name'],
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
