# Generated by Django 6.1.1 on 2026-09-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_gamesetting_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensitivityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('recommended_dpi', models.PositiveIntegerField()),
                ('recommended_sensitivity', models.CharField(max_length=50)),
                ('sensitivity_description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-saved_at', '-id'],
            },
        ),
    ]
